version: '3.4'

services:
  blazorhero:
    image: ${DOCKER_REGISTRY-}blazorhero
    build:
      context: .
      dockerfile: src/Server/Dockerfile
    environment:
      - "ConnectionStrings__DefaultConnection=Data Source=Data/blazorhero.db"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=securePassword123"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
      - blazorhero-data:/app/Data
    ports:
      - "5005:5005"
      - "5006:5006"
    restart: on-failure
    container_name: blazorhero

volumes:
  blazorhero-data:
